---
- hosts: aws_ec2
  user: ec2-user
  become: yes
  connection: ssh
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/london.pem"
    ansible_ssh_user: "ec2-user"
  tasks:
    - name: installing git in prod
      yum: name=git state=present
    - name: installing httpd web server
      yum: name=httpd state=present
    - name: restarting the httpd
      service: name=httpd state=restarted
    - name: getting the code into the serever
      git:
        repo: "https://github.com/Sivaprasad-Software/My-Mono-Project.git"
        dest: /var/www/html/
        version: "frontend"
...


